defaults:
  - trainer: default
model: "togethercomputer/RedPajama-INCITE-Base-3B-v1"
log_dir: "reward-model"
log_wandb: true
run_name: "hhrlhf_last"
wandb_entity: "shahules786"
max_length: 512
per_digit_tokens: False
special_tokens:
  eos_token: "</s>"
  sep_token: "<sep>"
  pad_token: "<pad>"
datasets:

  - AnthropicRLHF:
        split: ["train","test"]

validation_size: 0.1
deepspeed: true
deepspeed_config: "./config/trainer/zero.json"
