defaults:
  - trainer: default
model: "SummerSigh/Pythia410m-Instruct-SFT"
log_dir: "reward-model"
log_wandb: true
run_name: "hhrlhf"
wandb_entity: "shahules786"
max_length: 512
per_digit_tokens: False
special_tokens:
  eos_token: "</s>"
  sep_token: "<sep>"
  pad_token: "<pad>"
datasets:

  - AnthropicRLHF:
        split: ["train","test"]

validation_size: 0.1
